import yagmail
from secrets import EMAIL



def SendEmail(to, subject, body):
    print('Send email to {}'.format(to))
    
    EMAIL_FOOTER = '''
    \n
    This is an automated message generated by Austin Transportation's Arterial Management Division. To unsubscribe, contact john.clary@austintexas.gov.
    '''

    body = body + EMAIL_FOOTER

    yag = yagmail.SMTP(EMAIL['user'], EMAIL['password'])
    yag.send(to = to, subject = subject, contents = body)



def SendStaleEmail(elapsed_time, to):
    print('Send email to {}'.format(to))

    subject = 'DATA PROCESSING ALERT: KITS Status Data is {} mintues old'.format(str(elapsed_time))
    
    body = 'DATA PROCESSING ALERT: KITS intersection status data has not been updated for more than {} minutes.'.format(str(delta_minutes))
    
    EMAIL_FOOTER = '''
    \n
    This is an automated message generated by Austin Transportation's Arterial Management Division. To unsubscribe, contact john.clary@austintexas.gov.
    '''
    body = body + EMAIL_FOOTER

    yag = yagmail.SMTP(EMAIL['user'], EMAIL['password'])
    yag.send(to = to, subject = subject, contents = body)



def SendSocrataAlert(to, resource, socrata_response):
    print('Send email to {}'.format(to))
    
    subject = 'SOCRATA PUBLICATION FAILURE: Resource {} published with errors.'.format(resource)
    
    body = '''SOCRATA PUBLICATION FAILURE: Some records were unable to be published.
    \n
    RESPONSE: {}
    '''.format(socrata_response)
    
    EMAIL_FOOTER = '''
    \n
    This is an automated message generated by Austin Transportation's Arterial Management Division. To unsubscribe, contact john.clary@austintexas.gov.
    '''
    body = body + EMAIL_FOOTER

    yag = yagmail.SMTP(EMAIL['user'], EMAIL['password'])
    yag.send(to = to, subject = subject, contents = body)
