SCRIPTDIR = {
    "bcycle": ["bcycle_kiosk_pub", "bcycle_trip_pub"],
    "open_data": [
        "knack_data_pub",
        "pgrest_data_pub",
        "radar_count_pub",
        "sig_stat_pub",
        "cifs",
    ],
    "traffic_study": [
        "table_config",
        "traffic_study_cls",
        "traffic_study_loader",
        "traffic_study_locations",
        "traffic_study_spd",
        "traffic_study_vol",
    ],
    "data_tracker": [
        "backup",
        "detection_status_signals",
        "device_status",
        "device_status_log",
        "dms_msg_pub",
        "dms_msg_pub",
        "esb_xml_gen",
        "esb_xml_send",
        "fulc",
        "kits_cctv_push",
        "location_updater",
        "markings_agol",
        "metadata_updater",
        "secondary_signals_updater",
        "signal_pm_copier",
        "signal_request_ranker",
        "street_seg_updater",
        "task_orders",
        "tcp_business_days",
        "traffic_reports",
    ],
}
