cfg = {
    "tmc_activities": {
        "obj": "object_75",
        "ref_obj": ["object_83", "object_75"],
        "scene": "scene_514",
        "view": "view_1653",
        "template": "../config/esb/esb_csr_template_signals.xml",
        "emi_field": "field_1868",
        "esb_status_field": "field_1860",
        "esb_status_match": "READY_TO_SEND",
        "path_cert": "../config/esb/cert.pem",
        "path_key": "../config/esb/key.pem",
        "activity_details_fieldname": "TMC_ACTIVITY_DETAILS",
        "activity_name_fieldname": "TMC_ACTIVITY",
        "activity_id_field": "ATD_ACTIVITY_ID",
    },
    "signs_markings_activities": {
        "obj": "object_173",
        "ref_obj": ["object_173"],
        "scene": "scene_1228",
        "view": "view_3052",
        "template": "../config/esb/esb_csr_template_signsmarkings.xml",
        "emi_field": "field_3163",
        "esb_status_field": "field_3164",
        "esb_status_match": "READY_TO_SEND",
        "path_cert": "../config/esb/cert.pem",
        "path_key": "../config/esb/key.pem",
        "activity_details_fieldname": "CSR_ACTIVITY_DETAILS",
        "activity_name_fieldname": "CSR_ACTIVITY",
        "activity_id_field": "ATD_ACTIVITY_ID",
    },
}
