import yagmail

def send_email(to, subject, body, user, password):
    print('Send email to {}'.format(to))
    
    EMAIL_FOOTER = '''
    \n
    This is an automated message generated by Austin Transportation's Arterial Management Division. To unsubscribe, contact john.clary@austintexas.gov.
    '''

    body = body + EMAIL_FOOTER

    yag = yagmail.SMTP(user, password)
    yag.send(to = to, subject = subject, contents = body)


def send_socrata_alert(to, resource, socrata_response, user, password):
    print('Send email to {}'.format(to))
    
    subject = 'SOCRATA PUBLICATION FAILURE: Resource {} published with errors.'.format(resource)
    
    body = '''SOCRATA PUBLICATION FAILURE: Some records were unable to be published.
    \n
    RESPONSE: {}
    '''.format(socrata_response)
    
    EMAIL_FOOTER = '''
    \n
    This is an automated message generated by Austin Transportation's Arterial Management Division. To unsubscribe, contact john.clary@austintexas.gov.
    '''
    body = body + EMAIL_FOOTER

    yag = yagmail.SMTP(user, password)
    yag.send(to = to, subject = subject, contents = body)
